const synopsisData = {
    "Synopsis: Book 1: Fate and Foxfire": {
        isAccordion: false,
        items: [
            {
                "title": "Book 1: Fate and Foxfire",
                "content": "<p><strong>Core Conflict:</strong> The disappearance of <a href=\"#/search/Yume Minamoto / Sakura\" class=\"internal-link\">Yume Minamoto</a>, a sophisticated thought form, pulls expatriate <a href=\"#/search/Alex 'Bowie' Shepard\" class=\"internal-link\">Alex \"Bowie\" Shepard</a> and half-kitsune <a href=\"#/search/Mizuki / Hisoka\" class=\"internal-link\">Mizuki</a> into a conspiracy involving ancient magic, corporate greed (<a href=\"#/search/Mobex / Kagami Tenko Corporation\" class=\"internal-link\">Mobex / Kagami Tenko Corporation</a>), and the <a href=\"#/search/Yako Syndicate\" class=\"internal-link\">Yako Syndicate's</a> plan to awaken the reality-bending entity, <a href=\"#/search/The Kirin\" class=\"internal-link\">Kirin</a>, via the <a href=\"#/search/Project Tsunagari\" class=\"internal-link\">Tsunagari</a> project on <a href=\"#/search/Ikanajima Island\" class=\"internal-link\">Ikanajima Island</a>.</p><br><p><strong>Key Plot Points:</strong></p><ol><li>Yume disappears after a tarot reading with <a href=\"#/search/Ichiro Kobayashi\" class=\"internal-link\">Ichiro Kobayashi</a>.</li><li>Bowie investigates, guided by supernatural cats and cryptic clues (Tulpa puzzle).</li><li>Mizuki independently researches Yume, connecting it to her mother's disappearance and her own emerging heritage.</li><li>Bowie and Mizuki team up, uncovering artifacts and the nature of the <a href=\"#/search/The Æther\" class=\"internal-link\">Æther</a>.</li><li><a href=\"#/search/Shikako ('Onryō')\" class=\"internal-link\">Shikako</a> infiltrates Kagami Tenko, revealing their unethical experiments.</li><li>The group converges on Ikanajima Island.</li><li>Bowie uses the <a href=\"#/search/Kozyrev Mirror\" class=\"internal-link\">Kozyrev Mirror</a>, realities fracture, and the <a href=\"#/search/Celestial Council\" class=\"internal-link\">Celestial Council</a> enacts a stasis bubble.</li><li>Mizuki trains in the Æther, awakening her kitsune powers as <a href=\"#/search/Hisoka\" class=\"internal-link\">Hisoka</a>.</li><li>Climax on Ikanajima: Hisoka uses <a href=\"#/search/Foxfire\" class=\"internal-link\">foxfire</a>, <a href=\"#/search/Professor Shin'en Tajima\" class=\"internal-link\">Tajima</a> sacrifices himself, <a href=\"#/search/Commander Colt\" class=\"internal-link\">Commander Colt</a> is seemingly consumed by the nexus.</li><li>Yume \"accepts\" her fate, merging with <a href=\"#/search/Sakura\" class=\"internal-link\">Sakura's</a> essence.</li><li>Mizuki wipes Bowie's memory to protect him.</li></ol><br><p><strong>Resolution:</strong> Tsunagari project disrupted, Colt seemingly defeated, Yume transformed into Sakura, Mizuki embraces her heritage, Bowie's memory wiped but a seed of the truth remains (epilogue message from \"K\"/<a href=\"#/search/Kurai\" class=\"internal-link\">Kurai</a>).</p>"
            }
        ]
    },
    "Synopsis: Book 2: Family and Folklore": {
        isAccordion: false,
        items: [
            {
                "title": "Book 2: Family and Folklore",
                "content": "<p><strong>Core Conflict:</strong> <a href=\"#/search/Carly Shepard\" class=\"internal-link\">Carly Shepard</a>, living in the fractured <a href=\"#/search/New American Republic (NAR)\" class=\"internal-link\">New American Republic</a>, searches for her missing brother Alex. Her investigation leads her to a hidden research facility in the Appalachian Mountains—a sister site to <a href=\"#/search/Ikanajima Island\" class=\"internal-link\">Ikanajima</a>—and an uneasy alliance with <a href=\"#/search/Zenko Order\" class=\"internal-link\">Zenko</a> operative <a href=\"#/search/Shikako ('Onryō')\" class=\"internal-link\">Shikako</a> and the fugitive scientist <a href=\"#/search/Fredrik Sørensen\" class=\"internal-link\">Fredrik Sørensen</a>, uncovering local <a href=\"#/search/Folk Magic (NAR)\" class=\"internal-link\">folk magic</a>, <a href=\"#/search/Cryptids (NAR)\" class=\"internal-link\">cryptids</a> born of <a href=\"#/search/Ætheric Scarring (NAR)\" class=\"internal-link\">Ætheric scarring</a>, and the truth about her brother's \"split.\"</p><br><p><strong>Key Plot Points:</strong></p><ol><li>Carly's life in NAR is established; she begins her search for Alex.</li><li>Hits dead ends, suspects monitoring, contacts data wrangler <a href=\"#/search/Aoi\" class=\"internal-link\">Aoi</a>.</li><li>Aoi guides Carly to the Appalachian facility.</li><li>Shikako arrives in NAR on a mission to eliminate Sørensen.</li><li>Carly encounters local folk magic, cryptids (<a href=\"#/search/Squonk\" class=\"internal-link\">Squonk</a>, <a href=\"#/search/Thunderbird\" class=\"internal-link\">Thunderbird</a>), and signs of Sørensen.</li><li>Carly and Shikako meet and form an uneasy alliance with Sørensen.</li><li>They explore the facility, discovering its role as a sister site, the particle accelerator tapping <a href=\"#/search/Ley Lines\" class=\"internal-link\">ley lines</a>, and Ætheric experiments.</li><li>Carly finds NAR-Bowie in a <a href=\"#/search/Stasis Pods\" class=\"internal-link\">stasis pod</a>.</li><li>The facility's antagonist pushes the accelerator critical; NAR-Bowie is awakened and sacrifices himself to save Carly during the chaotic escape.</li><li>Shikako kills Sørensen.</li><li>Aoi informs Carly about \"another\" Bowie in Japan.</li></ol><br><p><strong>Resolution:</strong> Appalachian facility destroyed/contained, NAR-Bowie sacrifices himself, Sørensen eliminated, Carly learns of Japan-Bowie and prepares for a new journey.</p>"
            }
        ]
    },
    "Synopsis: Book 3: Faith and Finality": {
        isAccordion: false,
        items: [
            {
                "title": "Book 3: Faith and Finality",
                "content": "<p><strong>Core Conflict:</strong> <a href=\"#/search/Carly Shepard\" class=\"internal-link\">Carly Shepard</a> travels to Japan to find the \"other\" <a href=\"#/search/Alex 'Bowie' Shepard\" class=\"internal-link\">Alex Bowie</a>, grappling with grief and the nature of his fractured existence. The reunited group (Carly, Japan-Bowie, <a href=\"#/search/Mizuki / Hisoka\" class=\"internal-link\">Mizuki/Hisoka</a>, <a href=\"#/search/Shikako ('Onryō')\" class=\"internal-link\">Shikako</a>, <a href=\"#/search/Sakura\" class=\"internal-link\">Sakura</a>, <a href=\"#/search/Aoi\" class=\"internal-link\">Aoi</a>) must confront a new, nihilistic antagonist, <a href=\"#/search/Koda\" class=\"internal-link\">Koda</a>, who seeks to bring about \"<a href=\"#/search/Sunyata\" class=\"internal-link\">Sunyata</a>\" (the void) for all realities, forcing Bowie to embrace his full, merged self to save existence.</p><br><p><strong>Key Plot Points:</strong></p><ol><li>Carly travels to Japan, sponsored by Aoi.</li><li>Mizuki and Sakura discuss Bowie's duality.</li><li>Shikako detects Japan-Bowie's Ætheric ripples.</li><li>Carly meets the memory-wiped Japan-Bowie.</li><li>The group reunites; Shikako warns of lingering threats.</li><li>Sakura reveals Bowie's split nature to him, causing an existential crisis.</li><li>The <a href=\"#/search/Kitsune (Fox Spirits)\" class=\"internal-link\">Kitsune</a> Council discusses Koda's threat.</li><li>Bowie resolves to help, agreeing to be a decoy.</li><li>Return to <a href=\"#/search/Ikanajima Island\" class=\"internal-link\">Ikanajima Island</a>: Using <a href=\"#/search/Yume Minamoto / Sakura\" class=\"internal-link\">Yume/Sakura's</a> imprint as a catalyst, Bowie re-merges with his NAR-self's essence.</li><li>Koda is drawn by the re-merging and the final confrontation begins.</li><li>The team defeats Koda through combined effort.</li></ol><br><p><strong>Resolution:</strong> Koda defeated, Bowie is made whole, characters find new paths (Carly/Bowie rebuilding in <a href=\"#/search/New American Republic (NAR)\" class=\"internal-link\">NAR</a>, Mizuki/Sakura bonding, Shikako retiring). A hard-won, bittersweet victory.</p>"
            }
        ]
    }
};
