const themesData = {
    "Core Themes & Symbolism": [
        {
            "title": "Core Themes of the Saga",
            "content": "<p>The story explores several core themes:</p><ul><li><strong>Identity & Duality:</strong> Characters grapple with hidden heritages (<a href=\"#/search/Mizuki / Hisoka\" class=\"internal-link\">Mizuki/Hisoka</a>), fractured selves (<a href=\"#/search/Alex 'Bowie' Shepard\" class=\"internal-link\">Bowie</a>), concealed identities (<a href=\"#/search/Shikako ('Onryō')\" class=\"internal-link\">Onryō</a>), and the nature of what it means to be \"real\" (<a href=\"#/search/Yume Minamoto / Sakura\" class=\"internal-link\">Yume/Sakura</a>).</li><li><strong>Family & Connection:</strong> The powerful drive to find, protect, and understand family (Carly/Alex, Mizuki/Sakura). The formation of \"found families\" through shared trauma and purpose.</li><li><strong>The Balance:</strong> The central conflict often revolves around disrupting or restoring balance – between realities, between ancient magic and modern technology, and between factions like the <a href=\"#/search/Zenko Order\" class=\"internal-link\">Zenko</a> and <a href=\"#/search/Yako Syndicate\" class=\"internal-link\">Yako</a>.</li><li><strong>Sacrifice & Redemption:</strong> Characters repeatedly face choices requiring immense personal sacrifice (<a href=\"#/search/Professor Shin'en Tajima\" class=\"internal-link\">Tajima</a>, NAR-Bowie, Yume's transformation). Redemption is sought or offered, often through these sacrificial acts.</li><li><strong>Knowledge, Power, & Responsibility:</strong> The pursuit of dangerous knowledge (<a href=\"#/search/Mobex / Kagami Tenko Corporation\" class=\"internal-link\">Mobex</a>) and the immense responsibility that comes with wielding power (<a href=\"#/search/Hisoka\" class=\"internal-link\">Hisoka</a>'s awakening).</li></ul>"
        },
        {
            "title": "Symbolism & Deeper Meanings",
            "content": "<ul><li><strong>Foxes/Kitsune:</strong> Duality (Zenko vs. Yako), trickery, intelligence, transformation.</li><li><strong>Mirrors:</strong> Self-reflection, truth, illusion, fractured selves, windows to other realities.</li><li><strong>Eyes (especially Green):</strong> Windows to the soul, perception, connection to the Æther. Green eyes (Yume/Sakura) signify an otherworldly nature.</li><li><strong>Masks:</strong> Hidden identities, concealed motives, channeling power or tradition.</li><li><strong>Threads/Weaving:</strong> Interconnectedness, fate vs. free will, the danger of forcing connections (<a href=\"#/search/Project Tsunagari\" class=\"internal-link\">Tsunagari</a>).</li><li><strong>Sacrifice:</strong> A recurring theme necessary for the greater good, protection, or rebirth.</li><li><strong>Doors & Portals:</strong> Thresholds and transitions between states of being, worlds, or understanding.</li><li><strong>Trees (Cherry Blossom, Albino Pine):</strong> Life, impermanence, sacrifice, sacredness, and anomaly.</li></ul>"
        }
    ],
    "Character Dynamics & Arcs": [
        {
            "title": "Key Relationships & Dynamics",
            "content": "<p><strong><a href=\"#/search/Alex 'Bowie' Shepard\" class=\"internal-link\">Alex \"Bowie\" Shepard</a> & <a href=\"#/search/Mizuki / Hisoka\" class=\"internal-link\">Mizuki/Hisoka</a>:</strong> Begins as a cautious alliance, developing into mutual respect and reliance. Her memory wipe is a profound, tragic act of protection that creates a rift that must be healed in Book 3.</p><p><strong><a href=\"#/search/Carly Shepard\" class=\"internal-link\">Carly Shepard</a> & <a href=\"#/search/Alex 'Bowie' Shepard\" class=\"internal-link\">Alex \"Bowie\" Shepard</a>:</strong> A deep sibling bond that forms a core emotional arc about grief, identity, and redefined family after she witnesses NAR-Bowie's sacrifice and must meet Japan-Bowie.</p><p><strong><a href=\"#/search/Mizuki / Hisoka\" class=\"internal-link\">Mizuki/Hisoka</a> & <a href=\"#/search/Sakura\" class=\"internal-link\">Sakura</a>:</strong> A mother-daughter reunion that transcends typical bounds, involving shared power, guidance, and understanding of their unique Ætheric nature.</p><p><strong><a href=\"#/search/Shikako ('Onryō')\" class=\"internal-link\">Shikako</a> & <a href=\"#/search/Carly Shepard\" class=\"internal-link\">Carly Shepard</a>:</strong> An uneasy alliance forged in shared danger, developing into mutual respect for skills and resilience. Shikako's apology for Carly's loss after killing <a href=\"#/search/Fredrik Sørensen\" class=\"internal-link\">Sørensen</a> is a significant moment.</p><p><strong><a href=\"#/search/Aoi\" class=\"internal-link\">Aoi</a> & The Protagonist Group:</strong> Moves from a transactional relationship to one of personal investment and loyalty, especially after her partial manifestation on <a href=\"#/search/Ikanajima Island\" class=\"internal-link\">Ikanajima</a>.</p><p><strong><a href=\"#/search/Kurai\" class=\"internal-link\">Kurai</a> & <a href=\"#/search/Takuma\" class=\"internal-link\">Takuma</a>:</strong> A partnership where Takuma grounds Kurai as she navigates her frightening Ætheric sensitivity.</p>"
        },
        {
            "title": "Character Development & Craft Notes",
            "content": "<p><strong>Internal vs. External Stakes:</strong> Ensure each primary character has both compelling internal motivations/flaws and significant external challenges (e.g., Bowie’s external visa need vs. his internal search for purpose).</p><p><strong>Show, Don't Tell:</strong> Demonstrate traits through action and dialogue. Show Bowie's migraines (blue sparks, ozone), Shikako's competence through infiltration, or Kurai's anxiety through physical tells.</p><p><strong>Unique Voices:</strong> Each POV character should have a distinct voice. Bowie's confusion and determination; Carly's resilience and practicality; Kurai's anxiety and journalistic curiosity.</p><p><strong>Moral Grayness:</strong> Avoid purely good or evil characters. Antagonists can have understandable (if twisted) motivations (<a href=\"#/search/Commander Colt\" class=\"internal-link\">Colt's</a> resentment). Protagonists can make questionable choices (Mizuki wiping Bowie's memory).</p>"
        },
        {
            "title": "Character Voice & Dialogue Style Guide",
            "content": "<p><strong><a href=\"#/search/Alex 'Bowie' Shepard\" class=\"internal-link\">Alex 'Bowie' Shepard</a>:</strong> Informal, prone to mild sarcasm or bewildered humor. Asks questions to make sense of the bizarre. Internal monologue reveals his confusion and resolve.</p><p><strong><a href=\"#/search/Mizuki / Hisoka\" class=\"internal-link\">Mizuki/Hisoka</a>:</strong> (Mizuki) Guarded, analytical, precise. (Hisoka) More confident, powerful, commanding. Might use more formal or archaic phrasing for lore.</p><p><strong><a href=\"#/search/Carly Shepard\" class=\"internal-link\">Carly Shepard</a>:</strong> Pragmatic, direct, no-nonsense from her <a href=\"#/search/New American Republic (NAR)\" class=\"internal-link\">NAR</a> upbringing. Uses more colloquial American English.</p><p><strong><a href=\"#/search/Shikako ('Onryō')\" class=\"internal-link\">Shikako ('Onryō')</a>:</strong> Professional, calm, economical with words. Uses precise, tactical language.</p><p><strong><a href=\"#/search/Aoi\" class=\"internal-link\">Aoi</a>:</strong> Sharp, quick-witted, sarcastic. Mixes hacker slang with direct, business-like language.</p><p><strong><a href=\"#/search/Sakura\" class=\"internal-link\">Sakura</a> (Post-Merging):</strong> Wise, ancient, serene. Speaks with clarity and profound understanding, often philosophically.</p><p><strong><a href=\"#/search/Mr. Whispers\" class=\"internal-link\">Mr. Whispers</a>:</strong> Deep, resonant, calm, enigmatic. Speaks in riddles and metaphors.</p>"
        }
    ],
    "Narrative & Style Guides": [
        {
            "title": "Notes on Writing the Saga",
            "content": "<p><strong>Tone & Atmosphere:</strong> Blend elements of mystery, conspiracy thriller, urban fantasy, and light cosmic horror. Ground the fantastical in relatable human emotions.</p><p><strong>Pacing:</strong> Balance investigative sequences with action, character development, and lore exposition. Build suspense gradually.</p><p><strong>Worldbuilding Integration:</strong> Weave lore and rules naturally into the narrative through character discovery, dialogue, and environmental storytelling rather than info-dumps.</p>"
        },
        {
            "title": "Thematic Beats for Endings (Bittersweet/Pyrrhic Victory)",
            "content": "<p>This section applies to the overall trilogy ending, and potentially to the endings of individual books.</p><ul><li><strong>Resolution & Cost:</strong> The primary threat is averted, but victory is tinged with loss and sacrifice.</li><li><strong>Reflection & Transformation:</strong> Characters reflect on their journey and the personal transformations they've undergone.</li><li><strong>Expanded Perspective:</strong> Characters demonstrate a newfound understanding of broader cosmic implications.</li><li><strong>Future Paths:</strong> Characters begin to enact their plans for the future, embracing new roles.</li><li><strong>Seeds of Tomorrow:</strong> Subtle hints or unresolved elements suggest potential future adventures.</li><li><strong>Bonds Forged in Fire:</strong> Final moments showcase the strengthened bonds between surviving characters.</li><li><strong>Tempered Hope:</strong> Hope is not naive; it's tempered by the realization of the high cost of their victory.</li><li><strong>Contemplation & Openness:</strong> The narrative concludes on a note that invites audience reflection.</li></ul>"
        },
        {
            "title": "Potential Pacing Issues & Resolutions",
            "content": "<p><strong>Issue: Info Dumps.</strong> Resolution: Drip-feed information through dialogue, found lore (journals, files), and showing rather than telling.</p><p><strong>Issue: Investigation Lulls.</strong> Resolution: Interleave investigation with action or tension. Tie the investigation to personal stakes and a ticking clock.</p><p><strong>Issue: Overly Complex Metaphysics.</strong> Resolution: Ground concepts in character experience and tangible consequences. A few consistent core rules are key. Not everything needs to be explained.</p>"
        },
        {
            "title": "In-World Language & Naming Conventions",
            "content": "<p><strong>Japanese Language:</strong> Integrate naturally. Provide subtle context for less common terms. Honorifics generally informal among the main group.</p><p><strong>NAR Slang:</strong> Develop unique terms to reflect the fractured, post-apocalyptic culture.</p><p><strong>Corporate Jargon:</strong> Use project codenames (<a href=\"#/search/Project Sakura\" class=\"internal-link\">Sakura</a>, <a href=\"#/search/Project Tsunagari\" class=\"internal-link\">Tsunagari</a>) and technical jargon for fringe science.</p><p><strong>Faction Naming:</strong> The recurring kitsune theme (<a href=\"#/search/Zenko Order\" class=\"internal-link\">Zenko</a>, <a href=\"#/search/Yako Syndicate\" class=\"internal-link\">Yako</a>, <a href=\"#/search/Nogitsune Union\" class=\"internal-link\">Nogitsune</a>, <a href=\"#/search/Kogitsune Kai\" class=\"internal-link\">Kogitsune</a>) is a strong thematic link.</p>"
        },
        {
            "title": "Research & Inspiration List",
            "content": "<p><strong>Mythology & Folklore:</strong> Japanese (Kitsune, Kappa, Inari Ōkami), American (Squonk, Thunderbird, Pow Wow folk magic), Global (Ley Lines, Tulpas).</p><p><strong>Science & Fringe Science:</strong> Nikolai Kozyrev (Kozyrev Mirror), Particle Physics, Consciousness Studies, Cybernetics, AI.</p><p><strong>Literary & Media Genres:</strong> Cyberpunk (Blade Runner, Ghost in the Shell), Post-Apocalyptic (Fallout, The Road), Conspiracy Thrillers (The X-Files), Urban Fantasy (Dresden Files), Cosmic Horror (Lovecraftian elements).</p><p><strong>Philosophical Concepts:</strong> Existentialism, Nihilism, Eastern Philosophies (Buddhism, Shintoism).</p>"
        }
    ]
};
