const beingsData = {
    "Supernatural Beings & Entities": [
        {
            "title": "Kitsune (Fox Spirits)",
            "content": "<p><strong>Core Traits:</strong> Ancient, magical beings intrinsically linked to the <a href=\"#/search/The Æther\" class=\"internal-link\">Æther</a> and <a href=\"#/search/Inari Ōkami\" class=\"internal-link\">Inari</a> (goddess of rice, fertility). Grow more tails with age/power (<a href=\"#/search/Genseki\" class=\"internal-link\">Genseki</a> has four). Capable of <a href=\"#/search/Foxfire\" class=\"internal-link\">foxfire</a>, shapeshifting (implied), <a href=\"#/search/Phasing\" class=\"internal-link\">phasing</a>, and possessing deep esoteric knowledge. Bound by vows and a complex social structure.</p><br><p><strong>Factions & Types:</strong></p><ul><li><strong>Zenko (Celestial Kitsune):</strong> Generally benevolent, aligned with balance and Inari. Form the <a href=\"#/search/Celestial Council\" class=\"internal-link\">Celestial Council</a> (e.g., Inari-no-Kami, Chiyo, Genseki). Associated with purity (white fox).</li><li><strong>Yako (Field Kitsune):</strong> Mischievous, can be malevolent, tricksters (e.g., Hiroshi on the Council shows Yako-like tendencies/skepticism). Can possess humans.</li><li><strong>Nogitsune:</strong> Subset of Yako, agents of chaos. The <a href=\"#/search/Nogitsune Union\" class=\"internal-link\">Nogitsune Union</a> hacker group adopts the name.</li></ul><br><p><strong>Kitsune-kin:</strong> Individuals of mixed human-kitsune heritage (<a href=\"#/search/Mizuki / Hisoka\" class=\"internal-link\">Mizuki/Hisoka</a>). Possess latent kitsune abilities that can be awakened through trials or intense Ætheric experiences. Mizuki's father told her stories of kitsune.</p><br><p><strong>Kitsune Masks:</strong> Symbolic, used for disguise, channeling power, or signifying allegiance. Seen in Bowie's dreams and by the figures visiting Tajima (purple and blue accents). <a href=\"#/search/The Harbinger\" class=\"internal-link\">The Harbinger</a> wears one.</p>"
        },
        {
            "title": "Thought Forms (Tulpas/Egregores)",
            "content": "<p><strong>Nature:</strong> Beings created from concentrated thought, belief, and/or Ætheric energy, capable of physical manifestation. Formed by intense, sustained, focused consciousness and belief, amplified by Ætheric energy. <a href=\"#/search/Mobex Corporation\" class=\"internal-link\">Mobex</a> R&D files (<a href=\"#/search/Project Shinengata\" class=\"internal-link\">Project Shinengata</a>, <a href=\"#/search/Project Eidolon\" class=\"internal-link\">Project Eidolon</a>) detail theories. Discussed by Mobex researchers <a href=\"#/search/Alec & Javier\" class=\"internal-link\">Alec and Javier</a>.</p><br><p><strong>Stability & Independence:</strong> Varies. Simple servitors might be fleeting. Complex Egregores (like <a href=\"#/search/The Kirin\" class=\"internal-link\">Kirin</a>) can achieve independent sentience and immense power but may still require a host or continuous energy source.</p><br><p><strong>Vulnerability:</strong> Can be \"unmade\" or destabilized if their conceptual anchor is destroyed, energy source cut off, or a powerful counter-force applied.</p><br><p><strong>Examples:</strong></p><ul><li><strong><a href=\"#/search/Yume Minamoto / Sakura\" class=\"internal-link\">Yume Minamoto/Sakura</a>:</strong> A sophisticated, independent thought form (<a href=\"#/search/Project Sakura\" class=\"internal-link\">Project Sakura</a> by Mobex, <a href=\"#/search/Dr. Gordon Kionomiki\" class=\"internal-link\">Dr. Kionomiki</a> lead scientist), derived from/connected to the original Sakura (Mizuki's mother). Yume was \"built on pieces\" of the original Sakura. Her \"acceptance\" and merging with Sakura's essence suggests a re-integration or completion. She has distinctive green eyes.</li><li><strong><a href=\"#/search/The Kirin\" class=\"internal-link\">The Kirin</a>:</strong> The \"ultimate Egregore.\" A conscious, symbiotic weapon of immense power, capable of reshaping reality when bonded with a compatible host. Requires vast Ætheric energy. <a href=\"#/search/Yako Syndicate\" class=\"internal-link\">Yako's</a> goal is to control it. <a href=\"#/search/The Harbinger\" class=\"internal-link\">The Harbinger</a> warns Kurai about it.</li></ul>"
        },
        {
            "title": "Kappa (e.g., Taro)",
            "content": "<p><strong>Nature:</strong> Freshwater spirits from Japanese folklore.</p><br><p><strong>Traits:</strong> Possess unique characteristics: water-filled divot (sara) on their head which is the source of their power, politeness customs (bowing can spill their water, weakening them), and surprising strength. About 3ft tall, webbed feet/hands, green scales, yellow-brown belly. Taro has a \"plumage of eight felted petals\" on his head.</p><br><p><strong>Example (Taro):</strong> Encountered by <a href=\"#/search/Shikako ('Onryō')\" class=\"internal-link\">Shikako</a> in the <a href=\"#/search/Ikanajima Island\" class=\"internal-link\">Ikanajima Island</a> facility's sewer system. Aids Shikako's escape by providing scuba gear he \"collected.\" Aware of the <a href=\"#/search/Denki-Ōunagi\" class=\"internal-link\">Denki-Ōunagi</a> and the underwater ruins. Communicates with \"Yesssh\" and simple phrases. His adherence to customs (Shikako refilling his head-bowl earns his loyalty) provides a unique interaction point.</p>"
        },
        {
            "title": "The Harbinger",
            "content": "<p><strong>Physical Description:</strong> Robed figure. Wears a kitsune mask (this mask is sometimes described as faceless or can change).</p><br><p><strong>Overview:</strong> A mysterious, robed, kitsune-masked entity encountered by <a href=\"#/search/Kurai\" class=\"internal-link\">Kurai</a>, primarily in the <a href=\"#/search/The Æther\" class=\"internal-link\">Æther</a> but occasionally in the mundane world. Acts as a cryptic and often unsettling guide or warner.</p><br><p><strong>Role/Actions (Book 1):</strong> Appears to Kurai during her Ætheric projections and visions. Reveals Kurai's significance as a \"catalyst\" in a looming cosmic conflict. Warns of the <a href=\"#/search/Yako Syndicate\" class=\"internal-link\">Yako Syndicate</a>, the <a href=\"#/search/Kirin\" class=\"internal-link\">Kirin</a>, and the <a href=\"#/search/Convergence\" class=\"internal-link\">Convergence</a>. States Kurai's involvement is \"not voluntary.\"</p><br><p><strong>Notes/Potential Nature:</strong> Acts as a guide, source of power, and potentially an antagonist or trickster figure. May be testing Kurai and <a href=\"#/search/Takuma\" class=\"internal-link\">Takuma</a>. Linked to a civilization underneath the water of Ikanajima Island and to the <a href=\"#/search/Celestial Council\" class=\"internal-link\">Celestial Council</a>; potentially an avatar of Inari.</p>"
        },
        {
            "title": "Cryptids (NAR)",
            "content": "<p><strong><a href=\"#/search/Squonk\" class=\"internal-link\">Squonk</a>:</strong> American folklore creature. Cries before dissolving into a pool of tears if cornered or stressed. Its appearance/behavior in NAR is linked to Ætheric leakage from the Appalachian facility and resulting reality instability.</p><br><p><strong><a href=\"#/search/Thunderbird\" class=\"internal-link\">Thunderbird</a>:</strong> Massive, bird-like creatures from Native American legend. Sighted in NAR before \"the war\" and again during Ætheric surges from the Appalachian facility. Can manifest as beings of pure Ætheric energy. Their appearance often heralds significant events or disturbances. Locals like the <a href=\"#/search/\"Forest Witch\" (NAR)\" class=\"internal-link\">Forest Witch</a> are aware of their significance.</p><br><p><strong>\"Geists\":</strong> Local NAR term for minor paranormal phenomena. A catch-all for low-level Ætheric manifestations, echoes, or minor spirits stirred by the Appalachian facility's energy and reality distortions.</p>"
        },
        {
            "title": "Other Entities",
            "content": "<p><strong>Purple Hands:</strong> Hostile, translucent, shimmering Ætheric constructs or echoes. Grab Yume during Bowie's first rescue attempt in the Æther. Possibly remnants of failed experiments from <a href=\"#/search/Kagami Tenko Corporation\" class=\"internal-link\">Kagami Tenko</a>, psychic trauma, or guardians of a specific Ætheric domain. Seen in the <a href=\"#/search/Painter's Journal\" class=\"internal-link\">painter's journal</a>. Smell of moss/decay associated with them.</p><br><p><strong><a href=\"#/search/Denki-Ōunagi\" class=\"internal-link\">Denki-Ōunagi</a>:</strong> Colossal electric eels found in Ikanajima's underwater caverns. Highly dangerous.</p><br><p><strong>Talking Cherry Blossom Tree (Yume's Dream):</strong> A prophetic Ætheric entity appearing to Yume in her dream-like state within the Æther. Delivers cryptic messages.</p><br><p><strong><a href=\"#/search/Mr. Whispers\" class=\"internal-link\">Mr. Whispers</a>:</strong> A talking white Persian cat with ancient wisdom and deep knowledge of the Æther. Commands the Kitty Coalition.</p><br><p><strong><a href=\"#/search/Kitty Coalition\" class=\"internal-link\">Kitty Coalition</a>:</strong> Three synchronized tabby cats acting as agents of Mr. Whispers, guiding Bowie.</p><br><p><strong>Faceless Man:</strong> A figure seen by Kurai in visions and by Bowie in the scrying mirror. Represents the unknown, a universal archetype, or perhaps a specific recurring Ætheric echo.</p>"
        }
    ]
};
